### ISSUE TITLE
Add args?

### ISSUE THREAD

**Issue by FGasper** [houseabsolute/Devel-StackTrace#10]
Would you be opposed to adding the content of `@DB::args` to this, so that at a given level of the stack trace the object would indicate what the passed arguments were? It seems useful …

**Comment by autarch** [comment]
This is already available via the `$frame->args` method.

**Comment by FGasper** [comment]
Ah ok! 

Is it documented? I don’t see it:
https://metacpan.org/pod/Devel::StackTrace

**Comment by autarch** [comment]
See https://metacpan.org/pod/Devel::StackTrace::Frame

**Comment by FGasper** [comment]
Ah, thanks—sorry for the noise.
