### ISSUE TITLE
FEATURE REQUEST: Skipping packages based on regex or list

### ISSUE THREAD

**Issue by bpj** [houseabsolute/Devel-StackTrace#18]
I quite often find myself skipping frames at the top of the stack with

```perl
$t->frames( after_incl { $_->package !~ /^Foo::Bar\b|^Baz$/ } $t->frames );
```

```perl
my $where = first { $_->package !~ /^Foo::Bar\b|^Baz$/ } $t->frames;
```

i.e. not unlike what Carp::Clan does, and I can't help myself thinking that something like this (the first, filtering example) should be builtin; perhaps `skip_package` and `skip_class` params similar to the `ignore_*` params.

**Comment by autarch** [comment]
I'm not totally understanding your use case. You want to save the frames in the stack trace object but skip them when accessing the list of frames later? Why not use the frame filtering features that already exist? Do you only want to skip them sometimes?

**Comment by bpj** [comment]
I don't want to keep them, just remove matching frames at the top, but leave frames from the same package(s) further down the stack.  It isn't clear to me how I could do that with a `frame_filter` which gets called with one frame at a time.

**Comment by autarch** [comment]
You could so that with a filter sub that's a closure something like this:

```perl
my $keep_package = 0;
sub {
    my $caller = shift;
    if ( $caller->[0] ne 'My::Package' ) {
        $keep_package = 1;
        return 1;
    }
    return $keep_package;
}
```

Basically you make a closure that keeps track of whatever state you need to keep track of to make your decision.

**Comment by bpj** [comment]
OK but frankly I don't see the advantage compared to my current strategy.  A speed gain because the generation of frame objects is deferred and no `after_incl` code needs to be executed? Anything else?

Apparently I overestimated the general applicability of my use case. Sorry for the noise.
