### ISSUE TITLE
Do not get expected top frame after applying frame_filter

### ISSUE THREAD

**Issue by XSven** [houseabsolute/Devel-StackTrace#22]
I have an `Exception` class that consumes the `Throwable` role. Furthermore I have an `XMLException` class that extends the `Exception` class. In the

`sub BUILD { print STDERR Devel::StackTrace->new->as_string }`

method of the `Exception` class I am using `Devel::Stacktrace` to dump a trace like this

```
Trace begun at lib/Exception.pm line 21
Exception::BUILD('XMLException=HASH(0x1109928e8)', 'HASH(0x1109928b8)') called at (eval 110) line 78
XMLException::new(undef, 'message', 'cannot read line') called at (eval 109) line 26
Exception::new('XMLException', 'message', 'cannot read line') called at local/lib/perl5/Throwable.pm line 75
Throwable::throw('XMLException', 'message', 'cannot read line') called at t/parse.pl line 8
main::read_line at t/parse.pl line 12
main::parse at t/parse.pl line 16
eval {...} at t/parse.pl line 16
```
I have changed the trace I want to print using a `frame_filter`
```
sub BUILD {
  print STDERR Devel::StackTrace->new(
    frame_filter => sub { return 0 if $_[ 0 ]{ caller }[ 0 ]->DOES( 'Throwable' ); return 1 } )->as_string;
}
```
This is the expected result
```
Trace begun at t/parse.pl line 8
main::read_line at t/parse.pl line 12
main::parse at t/parse.pl line 16
eval {...} at t/parse.pl line 16
```

For me **the top frame of the filtered trace** is

`main::read_line at t/parse.pl line 12`

but when I use
```
sub BUILD {
  my $trace =
    Devel::StackTrace->new( frame_filter => sub { return 0 if $_[ 0 ]{ caller }[ 0 ]->DOES( 'Throwable' ); return 1 } );
  print STDERR $trace->next_frame->as_string, "\n";
}
```

I am getting

`Throwable::throw('XMLException', 'message', 'cannot read line') called at t/parse.pl line 8`

but why?

**Comment by autarch** [comment]
Thanks for the bug report. Can you provide a runnable code example that demonstrates this?

**Comment by XSven** [comment]
[devel-stacktrace.zip](https://github.com/houseabsolute/Devel-StackTrace/files/13284270/devel-stacktrace.zip)

You need to install `Moo`, `Throwable`, and `Devel::StackTrace`. Then run

`perl -Ilib t/parse.pl`

**Comment by XSven** [comment]
I have found my mistake sorry. The `frame_filter` was improper

```
frame_filter => sub {
  return 0 if $_[ 0 ]{ caller }[ 0 ]->DOES( 'Throwable' ) or $_[ 0 ]{ caller }[ 3 ] eq 'Throwable::throw';
  return 1;
}
```
I wanted to skip the call of `Throwable::throw` too but I haven't specified that.

As a suggestion: Maybe you could introduce a named parameter `ignore_role` that works similar like `ignore_class`.
